### ISSUE TITLE
Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry

### ISSUE THREAD

**Issue by allthesignals** [ggcity/leaflet-map#2]
Not sure what's going on here, followed instructions according to this thread [https://github.com/Polymer/polymer-starter-kit/issues/1123#issuecomment-408453390](url). Could this be related to the web component? 

```
bundle.js:4863 Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at Object.<anonymous> (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:4863:43)
    at t (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:9:17)
    at Object.<anonymous> (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:4489:11)
    at t (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:9:17)
    at Object.<anonymous> (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:4412:11)
    at t (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:9:17)
    at Object.<anonymous> (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:4321:11)
    at t (http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:9:17)
    at http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:28:16
    at http://127.0.0.1:8081/node_modules/@ggcity/leaflet-map/dist/bundle.js:29:3
```

**Comment by mooman** [comment]
This library was written with Preview version of Polymer 3 and hasn't been tested outside that ecosystem, unfortunately. I'm not too sure of your environment, but I'm betting it's probably that? Especially, the bundle.js was compiled with Polymer 3 preview...

I would try to compile it with your project with the newer version of Polymer.

There are plans in place to upgrade this to the stable version 3 or exploring lit-element.
